-- Find the least rented movie in each category.
WITH category_film AS (SELECT c.name, f.title, count(r.rental_id) AS times_rented
                       FROM category c
                                JOIN film_category fc USING (category_id)
                                JOIN film f USING (film_id)
                                JOIN inventory i USING (film_id)
                                JOIN rental r USING (inventory_id)
                       GROUP BY c.name, f.title
                       ORDER BY name),

     film_rank AS (SELECT name,
                          title,
                          times_rented,
                          row_number() over (partition by name order by times_rented ASC) AS rank
                   FROM category_film
                   GROUP BY name, title, times_rented)

SELECT name, title, times_rented
FROM film_rank
WHERE rank = 1
ORDER BY name;
-- Write a query to find the top 5 least rented movies in each category, along with the number of times each movie has been rented.
WITH category_film AS (SELECT c.name, f.title, count(r.rental_id) AS times_rented
                       FROM category c
                                JOIN film_category fc USING (category_id)
                                JOIN film f USING (film_id)
                                JOIN inventory i USING (film_id)
                                JOIN rental r USING (inventory_id)
                       GROUP BY c.name, f.title
                       ORDER BY name),

     film_rank AS (SELECT name,
                          title,
                          times_rented,
                          row_number() over (partition by name order by times_rented ASC) AS rank
                   FROM category_film
                   GROUP BY name, title, times_rented)

SELECT name, title, times_rented
FROM film_rank
WHERE rank <= 5
ORDER BY name;
-- Write a query to find the top 5 least profitable stores, along with the total revenue generated by each store.
-- Write a query to find the top 5 least profitable cities, along with the total revenue generated by each city.
-- Write a query to find out which month had the lowest number of rentals for each year.
-- Write a query to find out which store has generated less revenue from action films than comedy films.
-- Write a query to find out which country has generated less revenue from comedy films than drama films.
-- Write a query to find out which actor’s films have been rented out the least by customers from different countries.
-- Write a query to find out which category of films is least popular among customers from different countries.
-- Write a query to find out which store has generated less revenue from action films than comedy films.
-- Write a query to find out which country has generated less revenue from comedy films than drama films.
-- Write a query to find out which actor’s films have been rented out the least by customers from different countries.
-- Find the top 5 actors who have acted in the most number of unique categories.
-- Find the top 5 customers who have rented movies from the most number of unique categories.
-- Find the top 5 stores with the highest average rental rate for their movies.
-- Find the top 5 cities with the highest average rental rate for their movies.
-- Find the top 5 countries with the highest average rental rate for their movies.
-- Find the top 5 languages that have the highest average rental rate for their movies.
-- Find the top 5 ratings that have the highest average rental rate for their movies.
-- Find the top 5 actors who have acted in movies with the highest average rental rate.
-- Find the top 5 categories with the highest average rental rate for their movies.
-- Find the top 5 customers who have rented movies with the highest average rental rate.
-- Find the top 5 stores that have the most number of unique customers.
-- Find the top 5 cities that have the most number of unique customers.
-- Find the top 5 countries that have the most number of unique customers.
-- Find the top 5 languages that have the most number of unique customers.
-- Find the top 5 ratings that have the most number of unique customers.
-- Find the top 5 actors who have the most number of unique customers.
-- Find the top 5 categories that have the most number of unique customers.
-- Find the top 5 customers who have rented movies from the most number of unique actors.
-- Find the top 5 customers who have rented movies in the most number of unique languages.
-- Find the top 5 customers who have rented movies with the most number of unique ratings.
-- Find the actor who has acted in the most number of films in each language.
-- Find the customer who has rented the most number of films in each rating.
-- Find the store that has the most rentals in each month of the year.
-- Find the category of films that has the most rentals in each store.
-- Find the film that has been rented the most in each city.
-- Find the actor whose films have the highest average rental rate.
-- Find the customer who has rented films with the highest total rental rate.
-- Find the month that has the highest total rental rate for each year.
-- Find the city that has the highest average rental duration for its films.
-- Find the actor who has acted in films with the highest total length.
-- Find the customer who has rented films with the highest total length.
-- Find the category of films that has the highest average length.
-- Find the language that has the highest average length for its films.
-- Find the rating that has the highest average length for its films.
-- Find the store that has the highest average length for its films.
-- Find the city that has the highest average length for its films.
-- Find the country that has the highest average length for its films.
-- Find the month that has the highest average length for its films.
-- Find the actor whose films have been rented the most in each city.
-- Find the category of films that is most popular among customers from different stores.

-- Final Boss
-- Write a query to identify the top 5 customers who have rented the most diverse range of films in terms of categories, considering that diversity is measured by the number of unique combinations of categories rented by each customer.

-- Create a query to find the top 5 actors whose films have been rented out the least across all countries, excluding actors who have appeared in less than 10 films.

-- Implement a query to find the top 5 customers who have rented movies with the highest total rental rate per category, considering the rental rate of each movie.

-- Develop a query to find the top 5 cities where customers have the highest average rental duration for films belonging to categories with a "Parental Guidance" rating (PG).

-- Write a query to find the top 5 actors whose films have the highest average rental rate in countries where English is not the primary language spoken.

-- Create a query to find the top 5 customers who have rented movies with the highest total rental rate per language, considering the rental rate of each movie.

-- Implement a query to find the top 5 categories of films that have the highest average length, excluding categories with less than 10 films.

-- Write a query to find the top 5 customers who have rented movies from the most diverse range of countries, considering that diversity is measured by the number of unique countries from which movies have been rented by each customer.